### ISSUE TITLE
"env: node\r: No such file or directory" when run from CLI with nodejs 7.

### ISSUE THREAD

**Issue by mtbksouth** [MrMaxie/get-google-fonts#1]
Using node 7.10.1 and NPM 4.2.0 on OSX 10.11.6. 

Steps to reproduce:
Install globally (`npm i -g get-google-fonts`)
Run `get-google-fonts -i "https://fonts.googleapis.com/css?family=Luckiest+Guy"` or similar

Works with nodejs 8, though. Might just want to make 8 a minimum requirement. 

Thanks!

**Comment by MrMaxie** [comment]
The problem was that I mistakenly published the script with the Windows EOL and at the end of shebang there was the `\r\n` where `\n` it's correct EOL for unix-like systems.

I fixed it in newest version.
