### ISSUE TITLE
Tool downloads all the subsets of font instead of chosen

### ISSUE THREAD

**Issue by yumitsu** [MrMaxie/get-google-fonts#10]
**Describe the bug**
On invocation, `get-google-fonts` downloads all the font's subsets, instead of the one you chose on Google Fonts.

**To Reproduce**
```
$ get-google-fonts -i 'https://fonts.googleapis.com/css?family=Fira+Sans:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i&display=swap&subset=cyrillic' -o src/fonts/
Downloaded CSS with status code: 200 in 310ms
Found reference to 91 fonts
Saving Fira_Sans-200-cyrillic-ext1.woff2
Saving Fira_Sans-200-cyrillic2.woff2
Saving Fira_Sans-200-greek-ext3.woff2
Saving Fira_Sans-200-greek4.woff2
Saving Fira_Sans-200-vietnamese5.woff2
Saving Fira_Sans-200-latin-ext6.woff2
Saving Fira_Sans-200-latin7.woff2
```

**Expected behavior**
In my example there are 2 languages and 13 styles of font, so I guess it should be 26 in total - but ***not 91***.

**Desktop (please complete the following information):**
 - OS: macOS 10.12.6
 - Node: 12.4.0
 - Version: get-google-fonts 1.2.0

**Comment by MrMaxie** [comment]
Oh, I didn't seen it before. Actually there are 91 fonts URLs, but most of them are copies, because of unicode ranges. I'll fix it soon, thanks for that bug report :)

**Comment by MrMaxie** [comment]
Ok, I found point of that issue. All of those fonts are different (they are partials of full font file but with different characters range, that's fine). But Google serve always all fonts subsets on this URL for some reason, idk why, and I can't change that, sorry for that.

Forcing subset in other way than by URL will be awful, and not safe at all (for example some of font don't have those comments).

You can still force `get-google-fonts` to download only selected fonts by serving clipped CSS file. Save such file and serve e.g. using [serve](https://www.npmjs.com/package/serve) (then use `get-google-fonts -i localhost:5000/your_css_file.css`) or host online e.g. on gist (then use `get-google-fonts -i https://gist.github.com/your_new_file_random_token`).

PS for fastest remove unnecessary fonts from this file open console in browser and run `copy(document.querySelector('pre').innerText.replace(/(\/\* (?!cyrillic(?:-ext)?)[a-z-]+ \*\/[^}]*?})/gi, ''))`

**Comment by yumitsu** [comment]
Looks like Google fcked up again. Like it never happened, and look where are we.
Anyway, thanks for your labor!
