### ISSUE TITLE
Base64 fonts are not saved correctly

### ISSUE THREAD

**Issue by arstulke** [MrMaxie/get-google-fonts#14]
**Describe the bug**
When downloading fonts as Base64 URI, the output CSS file does not contain Base64 strings but the normal URL of the font files

**To Reproduce**
1. Execute the command `npm install get-google-fonts`
2. Execute the following code:
```
const GetGoogleFonts = require('get-google-fonts');
new GetGoogleFonts().download('https://fonts.googleapis.com/css?family=Open+Sans:400,600,700', { base64: true })
  .then(() => console.log('Done!'))
  .catch(() => console.log('Whoops!'));
```
3. Result (snippet):
```
/* cyrillic-ext */
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Open Sans Regular'), local('OpenSans-Regular'), url(https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFWJ0bbck.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
```

**Expected behavior**
The output file contains the contents of the font files as Base64 instead of plaintext URLs of the font files.
This `https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFWJ0bbck.woff2` should be something like this `data:font/woff2;base64,d09GMgABAAAAAEEwABE...`

**Desktop:**
 - OS: Windows 7
 - Node: v12.4.0
 - Version: 1.2.0 - 1.1.1

**Comment by arstulke** [comment]
I fixed the bug in a fork (https://github.com/arstulke/get-google-fonts). On the branch 'bugfix/base64-saving' there is a working version, based on an older working commit. I hope it's not too old. I merged the fix also on master but I cannot execute the master (before and after merge) locally.

It would be very nice if you could solve the bug and upload the fix to NPM.

**Comment by arstulke** [comment]
I created the pull request #15 fixing it

**Comment by MrMaxie** [comment]
Thanks, looks great ❤️
