### ISSUE TITLE
Module fails to download webfonts

### ISSUE THREAD

**Issue by J-Rojas** [MrMaxie/get-google-fonts#18]
**Describe the bug**

The module fails to download webfonts with an error: Error: connect ECONNREFUSED 127.0.0.1:443

**To Reproduce**

Install globally
run 'get-google-fonts -i <url>'

**Expected behavior**

Should not crash.

**Desktop (please complete the following information):**
MacOS 10.13
Node: v13.3

**Comment by MrMaxie** [comment]
Funny is the fact that we gave up using `request`, instead we used pure `https` for fear of package weight, and this change only brings problems
