### ISSUE TITLE
support for base64

### ISSUE THREAD

**Issue by landsman** [MrMaxie/get-google-fonts#2]
This is looks good: https://github.com/amio/embedded-google-fonts
Now I need have fonts in base64 for pdf a thats combo could be the best.

**Comment by MrMaxie** [comment]
7f4b021e17f548efcd85d9ca1c0e1379015a585b Ok, I added that feature in newest (1.1.1) version. 😄 
Enjoy!

**Comment by landsman** [comment]
Wow, thanks!
