### ISSUE TITLE
Add `strictSSL: false` to ignore SSL errors?

### ISSUE THREAD

**Issue by yfwz100** [MrMaxie/get-google-fonts#6]
https://github.com/MrMaxie/get-google-fonts/blob/1f166b361773019d8b9145a8363b2089cfef905e/main.js#L86-L92

Can you add options here (strictSSL: false) to ignore SSL errors in case the user is behind a company proxy?

**Comment by MrMaxie** [comment]
I added option to change that (in cli and in config object) in newest version. That option is called `strictSSL` in config and `--non-strict-ssl` in cli. So you can toggle default behaviour right now :)

Let me know, if everything works fine right now ^^

**Comment by yfwz100** [comment]
It works now, thanks!
